### ISSUE TITLE
Mac OS X: copy_object.spt fails

### ISSUE THREAD

**Issue by karolherbst** [KhronosGroup/SPIRV-LLVM-Translator#8] opened 2018-04-14 10:39 UTC
on travis-ci
```
Script:
--
/Users/travis/build/karolherbst/SPIRV-LLVM-Translator/build/bin/llvm-spirv /Users/travis/build/karolherbst/SPIRV-LLVM-Translator/llvm/tools/llvm-spirv/test/copy_object.spt -to-binary -o /Users/travis/build/karolherbst/SPIRV-LLVM-Translator/build/tools/llvm-spirv/test/test_output/Output/copy_object.spt.tmp.spv
/Users/travis/build/karolherbst/SPIRV-LLVM-Translator/build/bin/llvm-spirv -r /Users/travis/build/karolherbst/SPIRV-LLVM-Translator/build/tools/llvm-spirv/test/test_output/Output/copy_object.spt.tmp.spv -o /Users/travis/build/karolherbst/SPIRV-LLVM-Translator/build/tools/llvm-spirv/test/test_output/Output/copy_object.spt.tmp.bc
/Users/travis/build/karolherbst/SPIRV-LLVM-Translator/build/bin/llvm-dis < /Users/travis/build/karolherbst/SPIRV-LLVM-Translator/build/tools/llvm-spirv/test/test_output/Output/copy_object.spt.tmp.bc | /Users/travis/build/karolherbst/SPIRV-LLVM-Translator/build/bin/FileCheck /Users/travis/build/karolherbst/SPIRV-LLVM-Translator/llvm/tools/llvm-spirv/test/copy_object.spt --check-prefix=CHECK-LLVM
--
Exit Code: 1
Command Output (stderr):
--
/Users/travis/build/karolherbst/SPIRV-LLVM-Translator/llvm/tools/llvm-spirv/test/copy_object.spt:48:15: error: expected string not found in input
; CHECK-LLVM: %[[char:[0-9]+]] = alloca i8
              ^
<stdin>:1:1: note: scanning from here
; ModuleID = '<stdin>'
^
<stdin>:1:3: note: possible intended match here
; ModuleID = '<stdin>'
  ^
--
```

**Comment by MrSidims** [comment] 2022-09-21 16:31
It does look like the issue is no more, at least neither github actions nor travis exposing it. Closing, though can't find a fixing commit.

**Closed by MrSidims** 2022-09-21 16:31 UTC
