### ISSUE TITLE
Duplicate non-aggregate type declarations are not allowed

### ISSUE THREAD

**Issue by karolherbst** [KhronosGroup/SPIRV-LLVM-Translator#24] opened 2018-05-23 13:35 UTC
The current code generates two identical OpTypePointer declarations when using linked lists in OpenCL C. spir-val complains with this: "error: 14: Duplicate non-aggregate type declarations are not allowed. Opcode: TypePointer id: 5"

```OpenCL
struct Node {
        global struct Node *node;
};

kernel void test(global struct Node* out, global struct Node* in)
{
        out = in->node;
}
```

```SPIR-V
; SPIR-V
; Version: 1.0
; Generator: Khronos LLVM/SPIR-V Translator; 14
; Bound: 12
; Schema: 0
               OpCapability Addresses
               OpCapability Kernel
          %1 = OpExtInstImport "OpenCL.std"
               OpMemoryModel Physical64 OpenCL
               OpEntryPoint Kernel %7 "test"
               OpSource OpenCL_C 102000
               OpDecorate %11 FuncParamAttr NoCapture
         %11 = OpDecorationGroup
               OpGroupDecorate %11 %8 %9
               OpTypeForwardPointer %_ptr_CrossWorkgroup__struct_3 CrossWorkgroup
       %void = OpTypeVoid
  %_struct_3 = OpTypeStruct %_ptr_CrossWorkgroup__struct_3
%_ptr_CrossWorkgroup__struct_3 = OpTypePointer CrossWorkgroup %_struct_3
%_ptr_CrossWorkgroup__struct_3_0 = OpTypePointer CrossWorkgroup %_struct_3
          %6 = OpTypeFunction %void %_ptr_CrossWorkgroup__struct_3_0 %_ptr_CrossWorkgroup__struct_3_0
          %7 = OpFunction %void Pure %6
          %8 = OpFunctionParameter %_ptr_CrossWorkgroup__struct_3_0
          %9 = OpFunctionParameter %_ptr_CrossWorkgroup__struct_3_0
         %10 = OpLabel
               OpReturn
               OpFunctionEnd
```

**Comment by karolherbst** [comment] 2018-05-25 09:45
some tests which also generated invalid SPIRV like this:
- transcoding/RecursiveType.ll
- transcoding/OpImageQuerySize.ll

**Comment by karolherbst** [comment] 2018-05-25 09:55
Now after reading the SPIRV specification more carefully, especially section 2.8, I came to the conclusion that this should be a bug within spirv-val.

Section 2.8:
[...] Pointer types are also allowed to have multiple <id>s for the same opcode and operands, to allow for differing decorations (e.g., Volatile) or different decoration values (e.g., different Array Stride values for the ArrayStride). [...]

**Comment by karolherbst** [comment] 2018-05-25 10:01
Filed bug against spirv-val: https://github.com/KhronosGroup/SPIRV-Tools/issues/1577

**Comment by karolherbst** [comment] 2018-05-28 17:14
Okay, so for this to be valid SPIR-V code we either need the SPV_KHR_variable_pointers extension or have to use SPIR-V 1.3 whenever we end up with multiple OpTypePointer declarations being identical.

@AlexeySotkin Any suggestion what is the prefered thing to do here?

See https://github.com/KhronosGroup/SPIRV-Tools/pull/1580 for the upstream fix in spirv-val

**Comment by MrSidims** [comment] 2022-09-21 16:26
It does look like following to patches are addressing this issue:
```
commit 8a0235a239f34a19136eafd88c7f515537bab40a
Author: Viktoria Maximova <viktoria.maksimova@intel.com>
Date:   Tue Mar 22 12:37:49 2022 +0300

    Support complex recursive types that use an array of pointers (#1434)

    The use of pointer arrays inside the recursive type leads to the SPIR-V IR, where
    the TypePointer is declared after TypeArray. In turn, TypeArray can't handle the
    unknown element type, because the info from TypeForwardPointer is not used.

    Now the translator stores forward declared IDs to use them in backward
    translation. It actually means that the translator "knows" about the type but it
    would be handled later.

commit 5594d7c112edb21508526c6a3b0068df3a4201c6
Author: Alexey Sotkin <alexey.sotkin@intel.com>
Date:   Thu Mar 4 17:49:10 2021 +0300

    Redesign handling of forward pointers

    In some cases the current implementation doesn't create forward pointers
    when they are required. New approach is to create forward pointers
    during sorting of the type instructions.

    Signed-off-by: Alexey Sotkin <alexey.sotkin@intel.com>
```
and this patch proves, that the issue is fixed:
```
commit 1a800a0f65a231b1e0b5aedf0d99b0230563639b
Author: Sven van Haastregt <sven.vanhaastregt@arm.com>
Date:   Tue Jun 29 14:33:50 2021 +0100

    Run spirv-val for more tests
```
hence closing it

**Closed by MrSidims** 2022-09-21 16:26 UTC
