### ISSUE TITLE
function parameter attributes fails spir-v validation

### ISSUE THREAD

**Issue by airlied** [KhronosGroup/SPIRV-LLVM-Translator#376] opened 2019-11-11 05:05 UTC
; ModuleID = './CMakeFiles/builtins.link.spirv--.dir/generic/lib/subnormal_config.bc'
source_filename = "/home/airlied/devel/llvm-project/libclc/generic/lib/subnormal_config.cl"
target datalayout = "e-p:32:32-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024"
target triple = "spir-unknown-unknown"

; Function Attrs: convergent noinline nounwind optnone
define dso_local spir_func zeroext i1 @__clc_fp16_subnormals_supported() #0 {
entry:
  ret i1 false
}

; Function Attrs: convergent noinline nounwind optnone
define dso_local spir_func zeroext i1 @__clc_fp32_subnormals_supported() #0 {
entry:
  ret i1 false
}

; Function Attrs: convergent noinline nounwind optnone
define dso_local spir_func zeroext i1 @__clc_fp64_subnormals_supported() #0 {
entry:
  ret i1 false
}

attributes #0 = { convergent noinline nounwind optnone "correctly-rounded-divide-sqrt-fp-math"="false" "denorms-are-zero"="false" "disable-tail-calls"="false" "frame-pointer"="all" "less-precise-fpmad"="false" "min-legal-vector-width"="0" "no-infs-fp-math"="false" "no-jump-tables"="false" "no-nans-fp-math"="false" "no-signed-zeros-fp-math"="false" "no-trapping-math"="false" "stack-protector-buffer-size"="8" "unsafe-fp-math"="false" "use-soft-float"="false" }

!llvm.module.flags = !{!0}
!opencl.ocl.version = !{!1}
!opencl.spir.version = !{!2}
!llvm.ident = !{!3}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{i32 1, i32 0}
!2 = !{i32 1, i32 2}
!3 = !{!"clang version 10.0.0 (git://github.com/llvm/llvm-project b11e9fbb925a22e93f7571ca2bfdc74031762b2e)"}

produces:

               OpCapability Addresses
               OpCapability Linkage
               OpCapability Kernel
          %1 = OpExtInstImport "OpenCL.std"
               OpMemoryModel Physical32 OpenCL
               OpSource OpenCL_C 100000
               OpName %__clc_fp16_subnormals_supported "__clc_fp16_subnormals_supported"
               OpName %entry "entry"
               OpName %__clc_fp32_subnormals_supported "__clc_fp32_subnormals_supported"
               OpName %entry_0 "entry"
               OpName %__clc_fp64_subnormals_supported "__clc_fp64_subnormals_supported"
               OpName %entry_1 "entry"
               OpDecorate %11 FuncParamAttr Zext
         %11 = OpDecorationGroup
               OpDecorate %__clc_fp32_subnormals_supported LinkageAttributes "__clc_fp32_subnormals_supported" Export
               OpDecorate %__clc_fp64_subnormals_supported LinkageAttributes "__clc_fp64_subnormals_supported" Export
               OpDecorate %__clc_fp16_subnormals_supported LinkageAttributes "__clc_fp16_subnormals_supported" Export
               OpGroupDecorate %11 %__clc_fp16_subnormals_supported %__clc_fp32_subnormals_supported %__clc_fp64_subnormals_supported
       %bool = OpTypeBool
          %3 = OpTypeFunction %bool
      %false = OpConstantFalse %bool
     %__clc_fp16_subnormals_supported = OpFunction %bool DontInline %3
      %entry = OpLabel
               OpReturnValue %false
               OpFunctionEnd
    %__clc_fp32_subnormals_supported = OpFunction %bool DontInline %3
    %entry_0 = OpLabel
               OpReturnValue %false
               OpFunctionEnd
    %__clc_fp64_subnormals_supported = OpFunction %bool DontInline %3
    %entry_1 = OpLabel
               OpReturnValue %false
               OpFunctionEnd

which fails validation:
error: line 18: Invalid use of function result id 4[%__clc_fp16_subnormals_supported].
  OpGroupDecorate %11 %__clc_fp16_subnormals_supported %__clc_fp32_subnormals_supported %__clc_fp64_subnormals_supported

I'm not 100% sure if this is translation of validation bug, but I decided to start here.

**Comment by svenvh** [comment] 2020-02-03 11:42
There is a related issue on the validator: https://github.com/KhronosGroup/SPIRV-Tools/issues/3159

Once it's confirmed to be a validator bug, we can close this I suppose.

**Comment by AlexeySachkov** [comment] 2020-10-13 11:31
KhronosGroup/SPIRV-Tools#3159 is now closed because there was a patch submitted to the validator. So, it seems to me to be a validator bug, closing this tracker.

**Closed by AlexeySachkov** 2020-10-13 11:31 UTC
