### ISSUE TITLE
Mac OS X: composite_construct_vector.spt fails

### ISSUE THREAD

**Issue by karolherbst** [KhronosGroup/SPIRV-LLVM-Translator#7] opened 2018-04-14 10:38 UTC
detected with travis-ci
```
Script:
--
/Users/travis/build/karolherbst/SPIRV-LLVM-Translator/build/bin/llvm-spirv /Users/travis/build/karolherbst/SPIRV-LLVM-Translator/llvm/tools/llvm-spirv/test/composite_construct_vector.spt -to-binary -o /Users/travis/build/karolherbst/SPIRV-LLVM-Translator/build/tools/llvm-spirv/test/test_output/Output/composite_construct_vector.spt.tmp.spv
/Users/travis/build/karolherbst/SPIRV-LLVM-Translator/build/bin/llvm-spirv -r /Users/travis/build/karolherbst/SPIRV-LLVM-Translator/build/tools/llvm-spirv/test/test_output/Output/composite_construct_vector.spt.tmp.spv -o /Users/travis/build/karolherbst/SPIRV-LLVM-Translator/build/tools/llvm-spirv/test/test_output/Output/composite_construct_vector.spt.tmp.bc
/Users/travis/build/karolherbst/SPIRV-LLVM-Translator/build/bin/llvm-dis < /Users/travis/build/karolherbst/SPIRV-LLVM-Translator/build/tools/llvm-spirv/test/test_output/Output/composite_construct_vector.spt.tmp.bc | /Users/travis/build/karolherbst/SPIRV-LLVM-Translator/build/bin/FileCheck /Users/travis/build/karolherbst/SPIRV-LLVM-Translator/llvm/tools/llvm-spirv/test/composite_construct_vector.spt --check-prefix=CHECK-LLVM
--
Exit Code: 1
Command Output (stderr):
--
/Users/travis/build/karolherbst/SPIRV-LLVM-Translator/llvm/tools/llvm-spirv/test/composite_construct_vector.spt:48:15: error: expected string not found in input
; CHECK-LLVM: %[[vector:[0-9]+]] = getelementptr inbounds <4 x i32>, <4 x i32> addrspace(1)* %in, i64 %{{[0-9]*}}
              ^
<stdin>:1:1: note: scanning from here
; ModuleID = '<stdin>'
^
--
```

**Comment by MrSidims** [comment] 2022-09-21 16:31
It does look like the issue is no more, at least neither github actions nor travis exposing it. Closing, though can't find a fixing commit.

**Closed by MrSidims** 2022-09-21 16:31 UTC
